#!/usr/bin/env node

/**
 * pi-messenger installer
 *
 * Copies the npm package contents to ~/.pi/agent/extensions/pi-messenger.
 * No git dependency — the npm package IS the source.
 *
 * Usage:
 *   npx pi-messenger                # Install or update extension
 *   npx pi-messenger --remove       # Remove the extension
 *   npx pi-messenger --crew-install   # Show crew agent info
 *   npx pi-messenger --crew-uninstall # Remove crew agents
 */

import * as fs from "node:fs";
import * as path from "node:path";
import * as os from "node:os";
import { fileURLToPath } from "node:url";
import { execFileSync } from "node:child_process";

const __filename = fileURLToPath(import.meta.url);
const PACKAGE_DIR = path.dirname(__filename);
const EXTENSION_DIR = path.join(os.homedir(), ".pi", "agent", "extensions", "pi-messenger");
const AGENTS_DIR = path.join(os.homedir(), ".pi", "agent", "agents");
const BIN_DIR = path.join(os.homedir(), ".pi", "agent", "bin");
const CLI_WRAPPER_PATH = path.join(BIN_DIR, "pi-messenger-cli");

const CREW_AGENTS = [
	"crew-planner.md",
	"crew-interview-generator.md",
	"crew-plan-sync.md",
	"crew-worker.md",
	"crew-reviewer.md",
];

const DEPRECATED_AGENTS = [
	"crew-repo-scout.md",
	"crew-practice-scout.md",
	"crew-docs-scout.md",
	"crew-web-scout.md",
	"crew-github-scout.md",
	"crew-gap-analyst.md",
];

const pkg = JSON.parse(fs.readFileSync(path.join(PACKAGE_DIR, "package.json"), "utf-8"));
const VERSION = pkg.version;

// ─── CLI wrapper helpers ─────────────────────────────────────────────────────

/**
 * Resolve the path to pi's bundled jiti-cli.mjs via npm global prefix.
 * Returns null if pi is not installed or jiti is not found.
 */
function resolveJitiPath() {
	try {
		const npmPrefix = execFileSync("npm", ["prefix", "-g"], { encoding: "utf-8" }).trim();
		const jitiPath = path.join(npmPrefix, "lib", "node_modules",
			"@mariozechner", "pi-coding-agent", "node_modules",
			"@mariozechner", "jiti", "lib", "jiti-cli.mjs");
		if (fs.existsSync(jitiPath)) return jitiPath;
	} catch {}
	return null;
}

/**
 * Write the CLI wrapper script to ~/.pi/agent/bin/pi-messenger-cli.
 * The wrapper invokes pi's jiti to run the CLI TypeScript source directly.
 * Returns true if wrapper was created, false if jiti was not found.
 */
/**
 * Resolve the Homebrew bin directory (where pi, node, codex live).
 * This is the system-wide PATH location — works from any shell context.
 * ~/.pi/agent/bin/ is only in PATH inside pi sessions (getShellEnv), NOT
 * in regular terminals. The Homebrew bin is universally in PATH on macOS.
 */
function resolveBrewBinDir() {
	try {
		const npmPrefix = execFileSync("npm", ["prefix", "-g"], { encoding: "utf-8" }).trim();
		const brewBin = path.join(npmPrefix, "bin");
		if (fs.existsSync(brewBin)) return brewBin;
	} catch {}
	return null;
}

/**
 * Resolve a settings.json package entry to an absolute filesystem path.
 * Three-way resolution: npm: → global prefix, absolute → direct, relative → resolve against settings dir.
 */
function resolveSettingsEntry(entry) {
	if (entry.startsWith("npm:")) {
		const npmPrefix = execFileSync("npm", ["prefix", "-g"], { encoding: "utf-8" }).trim();
		return path.join(npmPrefix, "lib", "node_modules", entry.slice(4));
	}
	if (path.isAbsolute(entry)) return entry;
	// Relative paths are relative to settings.json's directory (~/.pi/agent/)
	const settingsDir = path.join(os.homedir(), ".pi", "agent");
	return path.resolve(settingsDir, entry);
}

function installCliWrapper(sourceDir) {
	const jitiPath = resolveJitiPath();
	if (!jitiPath) {
		console.error("⚠ CLI wrapper not created: pi not found (jiti unavailable).");
		console.error("  Install pi first, then re-run: npx pi-messenger");
		process.exitCode = 1;
		return false;
	}
	fs.mkdirSync(BIN_DIR, { recursive: true });
	const wrapper = `#!/bin/bash
# Generated by pi-messenger install — do not edit
JITI_PATH="${jitiPath}"
SOURCE_DIR="${sourceDir}"
if [ ! -f "$JITI_PATH" ]; then
  echo "pi-messenger-cli: jiti not found at $JITI_PATH" >&2
  echo "Pi may have been reinstalled. Re-run: npx pi-messenger" >&2
  exit 1
fi
if [ ! -f "$SOURCE_DIR/cli/index.ts" ]; then
  echo "pi-messenger-cli: source not found at $SOURCE_DIR/cli/index.ts" >&2
  echo "Re-run: npx pi-messenger" >&2
  exit 1
fi
exec node "$JITI_PATH" "$SOURCE_DIR/cli/index.ts" "$@"
`;
	fs.writeFileSync(CLI_WRAPPER_PATH, wrapper, { mode: 0o755 });

	// Symlink into Homebrew bin so the CLI is available from ANY shell context,
	// not just inside pi sessions. ~/.pi/agent/bin/ is only in PATH when pi's
	// getShellEnv() prepends it — regular terminals don't have it.
	const brewBin = resolveBrewBinDir();
	if (brewBin) {
		const symlinkPath = path.join(brewBin, "pi-messenger-cli");
		try {
			// Remove existing symlink/file if present (idempotent)
			if (fs.existsSync(symlinkPath)) fs.unlinkSync(symlinkPath);
			fs.symlinkSync(CLI_WRAPPER_PATH, symlinkPath);
		} catch (err) {
			console.error(`⚠ Could not create symlink at ${symlinkPath}: ${err.message}`);
			console.error("  pi-messenger-cli will only work inside pi sessions.");
		}
	}

	return true;
}

const args = process.argv.slice(2);
const isRemove = args.includes("--remove") || args.includes("-r");
const isCrewInstall = args.includes("--crew-install");
const isCrewUninstall = args.includes("--crew-uninstall");
const isHelp = args.includes("--help") || args.includes("-h");

if (isHelp) {
	console.log(`
pi-messenger v${VERSION} - Multi-agent coordination for pi

Usage:
  npx pi-messenger                Install or update extension
  npx pi-messenger --remove       Remove the extension
  npx pi-messenger --crew-install   Show crew agent info
  npx pi-messenger --crew-uninstall Remove crew agents
  npx pi-messenger --help          Show this help

Extension directory: ${EXTENSION_DIR}
`);
	process.exit(0);
}

// ─── Crew install ────────────────────────────────────────────────────────────

if (isCrewInstall) {
	const agentsDir = path.join(EXTENSION_DIR, "crew", "agents");
	if (!fs.existsSync(agentsDir)) {
		console.log("Extension not installed. Run: npx pi-messenger");
		process.exit(1);
	}

	const agents = fs.readdirSync(agentsDir).filter(f => f.endsWith(".md"));
	console.log(`Crew agents (${agents.length}) ship with the extension:`);
	console.log(`  ${agentsDir}`);
	for (const agent of agents) {
		console.log(`  - ${agent}`);
	}
	console.log("\nTo customize, copy an agent to .pi/messenger/crew/agents/ and edit it.");
	process.exit(0);
}

// ─── Crew uninstall ──────────────────────────────────────────────────────────

if (isCrewUninstall) {
	let removed = 0;

	for (const agent of [...CREW_AGENTS, ...DEPRECATED_AGENTS]) {
		const target = path.join(AGENTS_DIR, agent);
		if (fs.existsSync(target)) {
			fs.unlinkSync(target);
			removed++;
		}
	}

	console.log(removed > 0
		? `Removed ${removed} crew agent(s) from ${AGENTS_DIR}`
		: "Nothing to remove");
	process.exit(0);
}

// ─── Extension remove ────────────────────────────────────────────────────────

if (isRemove) {
	// Always clean up CLI wrapper + Homebrew symlink, even if extension dir is already gone
	const brewBin = resolveBrewBinDir();
	if (brewBin) {
		const symlinkPath = path.join(brewBin, "pi-messenger-cli");
		if (fs.existsSync(symlinkPath)) {
			try { fs.unlinkSync(symlinkPath); } catch {}
		}
	}
	if (fs.existsSync(CLI_WRAPPER_PATH)) {
		fs.unlinkSync(CLI_WRAPPER_PATH);
		console.log("Removed CLI: " + CLI_WRAPPER_PATH);
	}
	if (fs.existsSync(EXTENSION_DIR)) {
		fs.rmSync(EXTENSION_DIR, { recursive: true });
		console.log("Removed pi-messenger from " + EXTENSION_DIR);
	} else {
		console.log("pi-messenger extension not installed");
	}
	process.exit(0);
}

// Already running from the extension dir (e.g. local dev)
if (path.resolve(PACKAGE_DIR) === path.resolve(EXTENSION_DIR)) {
	console.log(`Already installed at ${EXTENSION_DIR} (v${VERSION})`);
	process.exit(0);
}

// ─── Collision guard: check settings.json packages ───────────────────────────
// If pi-messenger is already registered as a package (local path or npm),
// copying to extensions/ creates a collision — two copies loaded by pi.
// On collision, the CLI wrapper is created pointing to the RESOLVED settings
// entry path (not PACKAGE_DIR), so it always points to the live source.

const isForce = args.includes("--force") || args.includes("-f");
const settingsPath = path.join(os.homedir(), ".pi", "agent", "settings.json");

if (!isForce && fs.existsSync(settingsPath)) {
	let settings;
	try {
		settings = JSON.parse(fs.readFileSync(settingsPath, "utf-8"));
	} catch (e) {
		// Fail closed — malformed settings.json could hide a collision
		console.error(`⚠ Cannot parse ${settingsPath}: ${e.message}`);
		process.exit(1);
	}
	if (settings) {
		const packages = settings.packages ?? [];
		const collision = packages.find((entry) => {
			if (typeof entry !== "string") return false;
			const name = entry.startsWith("npm:") ? entry.slice(4) : path.basename(entry);
			return name === "pi-messenger" || name.startsWith("pi-messenger-");
		});
		if (collision) {
			let resolved;
			try {
				resolved = resolveSettingsEntry(collision);
			} catch (err) {
				console.error(`⚠ Cannot resolve "${collision}": ${err.message}`);
				console.error("Extension copy skipped. CLI wrapper not updated.");
				process.exit(1);
			}
			if (installCliWrapper(resolved)) {
				console.log(`⚠ Extension copy skipped (registered at ${collision}).`);
				console.log(`CLI:      pi-messenger-cli → ${CLI_WRAPPER_PATH}`);
				process.exit(0);
			}
			console.error(`⚠ Registered at ${collision} but CLI wrapper failed (jiti not found).`);
			console.error("Install pi first, then re-run: node install.mjs");
			process.exit(1);
		}
	}
}

// No collision — standard install path
const wrapperCreated = installCliWrapper(PACKAGE_DIR);

const isUpdate = fs.existsSync(EXTENSION_DIR);

// Warn if existing install is a git clone from the old installer
if (isUpdate && fs.existsSync(path.join(EXTENSION_DIR, ".git"))) {
	console.log("Existing install is a git clone. Remove it first:\n");
	console.log("  npx pi-messenger --remove && npx pi-messenger");
	process.exit(1);
}

// Clean slate for updates so removed files don't linger between versions
if (isUpdate) {
	fs.rmSync(EXTENSION_DIR, { recursive: true });
}

const SKIP = new Set([".git", "node_modules", ".DS_Store"]);

function copyDir(src, dest) {
	fs.mkdirSync(dest, { recursive: true });
	for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
		if (SKIP.has(entry.name)) continue;
		const srcPath = path.join(src, entry.name);
		const destPath = path.join(dest, entry.name);
		if (entry.isDirectory()) {
			copyDir(srcPath, destPath);
		} else {
			fs.copyFileSync(srcPath, destPath);
		}
	}
}

copyDir(PACKAGE_DIR, EXTENSION_DIR);

// Update CLI wrapper to point to canonical extension dir (instead of PACKAGE_DIR)
installCliWrapper(EXTENSION_DIR);

const action = isUpdate ? "Updated" : "Installed";
console.log(`${action} pi-messenger v${VERSION} → ${EXTENSION_DIR}

Tools:    pi_messenger
Commands: /messenger, /messenger config
CLI:      pi-messenger-cli → ${CLI_WRAPPER_PATH}
Docs:     ${EXTENSION_DIR}/README.md`);
