/**
 * Tests for CLI wrapper install/remove/idempotent/graceful-failure (spec 007)
 *
 * T5: Wrapper creation/removal
 * T6: Graceful failure (stale jiti, missing source)
 * T8: AC5 crew-spawned integration
 */

import { describe, it, expect, afterEach } from "vitest";
import { execFileSync } from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";
import * as os from "node:os";

const roots = new Set<string>();

function createTmpDir(prefix: string): string {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), `cli-wrapper-test-${prefix}-`));
  roots.add(dir);
  return dir;
}

afterEach(() => {
  for (const root of roots) {
    try { fs.rmSync(root, { recursive: true, force: true }); } catch {}
  }
  roots.clear();
});

/**
 * Write a CLI wrapper script to a temp bin dir and return paths.
 */
function writeWrapper(
  binDir: string,
  jitiPath: string,
  sourceDir: string,
): string {
  fs.mkdirSync(binDir, { recursive: true });
  const wrapperPath = path.join(binDir, "pi-messenger-cli");
  const wrapper = `#!/bin/bash
# Generated by pi-messenger install — do not edit
JITI_PATH="${jitiPath}"
SOURCE_DIR="${sourceDir}"
if [ ! -f "$JITI_PATH" ]; then
  echo "pi-messenger-cli: jiti not found at $JITI_PATH" >&2
  echo "Pi may have been reinstalled. Re-run: npx pi-messenger" >&2
  exit 1
fi
if [ ! -f "$SOURCE_DIR/cli/index.ts" ]; then
  echo "pi-messenger-cli: source not found at $SOURCE_DIR/cli/index.ts" >&2
  echo "Re-run: npx pi-messenger" >&2
  exit 1
fi
exec node "$JITI_PATH" "$SOURCE_DIR/cli/index.ts" "$@"
`;
  fs.writeFileSync(wrapperPath, wrapper, { mode: 0o755 });
  return wrapperPath;
}

// Resolve the real jiti path for integration tests
function getRealJitiPath(): string | null {
  try {
    const npmPrefix = execFileSync("npm", ["prefix", "-g"], { encoding: "utf-8" }).trim();
    const jitiPath = path.join(npmPrefix, "lib", "node_modules",
      "@mariozechner", "pi-coding-agent", "node_modules",
      "@mariozechner", "jiti", "lib", "jiti-cli.mjs");
    if (fs.existsSync(jitiPath)) return jitiPath;
  } catch {}
  return null;
}

// ─── T5: Wrapper creation/removal ──────────────────────────────────────────

describe("CLI wrapper creation/removal (T5)", () => {
  it("creates wrapper with correct content and permissions", () => {
    const binDir = createTmpDir("bin");
    const sourceDir = "/tmp/fake-source";
    const jitiPath = "/tmp/fake-jiti.mjs";

    const wrapperPath = writeWrapper(binDir, jitiPath, sourceDir);

    expect(fs.existsSync(wrapperPath)).toBe(true);
    const stat = fs.statSync(wrapperPath);
    // Check executable bit (owner)
    expect(stat.mode & 0o100).toBeTruthy();

    const content = fs.readFileSync(wrapperPath, "utf-8");
    expect(content).toContain("#!/bin/bash");
    expect(content).toContain(jitiPath);
    expect(content).toContain(sourceDir);
    expect(content).toContain("exec node");
  });

  it("removal works even when extension dir does not exist", () => {
    const binDir = createTmpDir("bin-remove");
    const wrapperPath = writeWrapper(binDir, "/tmp/jiti", "/tmp/src");

    // Wrapper exists
    expect(fs.existsSync(wrapperPath)).toBe(true);

    // Delete it (simulating --remove)
    fs.unlinkSync(wrapperPath);
    expect(fs.existsSync(wrapperPath)).toBe(false);
    // No extension dir ever existed — cleanup is unconditional
  });

  it("idempotent: overwriting produces correct content", () => {
    const binDir = createTmpDir("bin-idem");
    const jitiPath = "/tmp/jiti-v1.mjs";
    const sourceDir = "/tmp/source-v1";

    // First write
    writeWrapper(binDir, jitiPath, sourceDir);

    // Second write with different source
    const newSource = "/tmp/source-v2";
    const wrapperPath = writeWrapper(binDir, jitiPath, newSource);

    const content = fs.readFileSync(wrapperPath, "utf-8");
    expect(content).toContain(newSource);
    expect(content).not.toContain(sourceDir);
  });
});

// ─── T6: Graceful failure ──────────────────────────────────────────────────

describe("CLI wrapper graceful failure (T6)", () => {
  it("exits 1 with clear error when jiti path is stale", () => {
    const binDir = createTmpDir("bin-stale");
    const wrapperPath = writeWrapper(binDir, "/tmp/nonexistent-jiti.mjs", process.cwd());

    try {
      execFileSync(wrapperPath, ["--help"], { encoding: "utf-8", timeout: 10000 });
      expect.unreachable("should have thrown");
    } catch (err: any) {
      expect(err.status).toBe(1);
      expect(err.stderr.toString()).toContain("jiti not found");
      expect(err.stderr.toString()).toContain("Re-run: npx pi-messenger");
    }
  });

  it("exits 1 with clear error when source dir is missing", () => {
    // Use real jiti if available, otherwise skip
    const jitiPath = getRealJitiPath();
    if (!jitiPath) {
      console.log("Skipping: jiti not found (pi not installed)");
      return;
    }

    const binDir = createTmpDir("bin-nosrc");
    const wrapperPath = writeWrapper(binDir, jitiPath, "/tmp/nonexistent-source-dir");

    try {
      execFileSync(wrapperPath, ["--help"], { encoding: "utf-8", timeout: 10000 });
      expect.unreachable("should have thrown");
    } catch (err: any) {
      expect(err.status).toBe(1);
      expect(err.stderr.toString()).toContain("source not found");
      expect(err.stderr.toString()).toContain("Re-run: npx pi-messenger");
    }
  });
});

// ─── T8: AC5 crew-spawned integration ──────────────────────────────────────

describe("CLI wrapper crew-spawned integration (T8/AC5)", () => {
  it("crew-spawned worker can call pi-messenger-cli status", () => {
    const jitiPath = getRealJitiPath();
    if (!jitiPath) {
      console.log("Skipping: jiti not found (pi not installed)");
      return;
    }

    const tmpDir = createTmpDir("ac5");
    const binDir = path.join(tmpDir, "bin");
    const messengerDir = path.join(tmpDir, "messenger");
    const registryDir = path.join(messengerDir, "registry");
    const inboxDir = path.join(messengerDir, "inbox");

    // Create dirs
    fs.mkdirSync(registryDir, { recursive: true });
    fs.mkdirSync(inboxDir, { recursive: true });

    // Pre-register worker (crew-spawned mode requires this)
    const workerName = "TestWorker007";
    fs.writeFileSync(
      path.join(registryDir, `${workerName}.json`),
      JSON.stringify({
        name: workerName,
        pid: process.pid,  // Current process — passes isProcessAlive check
        sessionId: "test-session",
        cwd: process.cwd(),
        model: "test",
        startedAt: new Date().toISOString(),
        isHuman: false,
        session: { toolCalls: 0, tokens: 0, filesModified: [] },
        activity: { lastActivityAt: new Date().toISOString() },
      }),
    );

    // Create wrapper pointing to real source
    const sourceDir = path.resolve(__dirname, "../..");
    const wrapperPath = writeWrapper(binDir, jitiPath, sourceDir);

    // Execute pi-messenger-cli status in crew-spawned mode
    // status is lightweight — doesn't require crew plan/tasks, just the registry
    const result = execFileSync(wrapperPath, ["status"], {
      encoding: "utf-8",
      timeout: 30000,
      env: {
        ...process.env,
        PI_CREW_WORKER: "1",
        PI_AGENT_NAME: workerName,
        PI_MESSENGER_DIR: messengerDir,
        PATH: `${binDir}:${process.env.PATH}`,
      },
      cwd: process.cwd(),
    });

    // Should succeed — proves crew-spawned bootstrap + jiti execution + CLI invocation
    expect(result).toContain(workerName);
  });
});
